/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 用戶端丟棄 token 即登出（無狀態 JWT）；此端點供審計/對稱性 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 依角色/參與過濾（director/white/admin 見全部；其餘見自己參與的） */
        get: operations["listSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description action: START|PAUSE|RESUME|END|ROLLBACK (+checkpoint_tick) */
        post: operations["sessionLifecycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** @description faction-scoped 全量快照（重連用） */
        get: operations["getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** @description faction-scoped 單位（一般角色見己方；全知見全部；White Cell 可 as_faction 切換視角） */
        get: operations["listUnits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/inject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description White Cell ad-hoc 事件注入（SPEC §11.3）。限 EXERCISE_DIRECTOR / WHITE_CELL_STAFF。 */
        post: operations["injectEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/control": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description White Cell 時間控制（PAUSE/RESUME/ROLLBACK，SPEC §12/§3.4）。限統裁。 */
        post: operations["sessionControl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** @description 列出 session 指令（pending + 歷史，faction-scoped） */
        get: operations["listOrders"];
        put?: never;
        /** @description 驗證 + 物理預檢；通過 → 201 VALIDATED，不可行 → 422（order 落庫為 REJECTED） */
        post: operations["issueOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/orders/{oid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
                oid: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cancelOrder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/ai/consult": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description {role, query} → 202 + task_id（非同步；逾時 doctrine fallback） */
        post: operations["aiConsult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/ai/tasks/{tid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
                tid: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get: operations["aiTaskStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/injects": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description White Cell only */
        post: operations["mselInject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** @description ?after_seq=&types=  分頁、faction-scoped 投影 */
        get: operations["queryLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/aar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getAAR"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listScenarios"];
        put?: never;
        post: operations["uploadScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/plugins/{name}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["PluginName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["togglePlugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 統一錯誤格式（app.api.errors 產出） */
        Error: {
            error: {
                /**
                 * @description error code 枚舉（O3.1 Order pipeline 部分）
                 * @enum {string}
                 */
                code: "INTERNAL_ERROR" | "AUTH_INVALID_CREDENTIALS" | "AUTH_INVALID_TOKEN" | "AUTH_TOKEN_EXPIRED" | "AUTH_FORBIDDEN" | "SESSION_NOT_FOUND" | "SCENARIO_NOT_FOUND" | "ORDER_NOT_FOUND" | "ORDER_INVALID_PAYLOAD" | "ORDER_UNIT_NOT_FOUND" | "ORDER_PERMISSION_DENIED" | "ORDER_INVALID_TRANSITION" | "ORDER_UNIT_NO_POSITION" | "ORDER_UNREACHABLE" | "ORDER_TARGET_NOT_FOUND" | "ORDER_NO_LOS" | "ORDER_OUT_OF_RANGE" | "ORDER_NO_AMMO" | "ORDER_PRECHECK_FAILED" | "ORDER_ROE_VIOLATION" | "TERRAIN_UNAVAILABLE" | "FACTION_INVALID" | "AI_DISABLED" | "AI_OUTPUT_REJECTED";
                message: string;
                details?: Record<string, never>;
            };
        };
        /** @enum {string} */
        UserRole: "EXERCISE_DIRECTOR" | "WHITE_CELL_STAFF" | "COMMANDER" | "STAFF" | "OBSERVER" | "ANALYST" | "ADMIN";
        /** @description 想定定義的陣營 id（SPEC §12.1/ADR 006）；WHITE_CELL 為統裁保留字。 */
        Faction: string;
        LoginRequest: {
            username: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        /** @description access（短效）+ refresh（長效）JWT 對 */
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @constant */
            token_type: "bearer";
            /** @description access token 剩餘秒數 */
            expires_in: number;
        };
        AccessToken: {
            access_token: string;
            /** @constant */
            token_type: "bearer";
            expires_in: number;
        };
        CurrentUser: {
            id: string;
            username: string;
            role: components["schemas"]["UserRole"];
        };
        /** @description lobby 列表項（faction/角色過濾後） */
        SessionSummary: {
            id: string;
            name: string;
            scenario_id?: string | null;
            mode: string;
            status: string;
            /** @description 呼叫者在此 session 的陣營（非參與者為 null） */
            my_faction?: string | null;
        };
        UnitView: {
            id: string;
            designation: string;
            unit_level: string;
            faction: string;
            lat?: number | null;
            lng?: number | null;
            health: number;
            comms: string;
        };
        CreateSessionRequest: {
            name: string;
            scenario_id?: string | null;
            /**
             * @default REALTIME
             * @enum {string}
             */
            mode: "REALTIME" | "WEGO" | "IGO_UGO";
        };
        InjectRequest: {
            event_type: string;
            payload?: Record<string, never>;
            /** @description 受眾陣營（null＝廣播） */
            faction?: string | null;
        };
        InjectResponse: {
            seq: number;
        };
        ControlRequest: {
            /** @enum {string} */
            action: "PAUSE" | "RESUME" | "ROLLBACK";
            /** @description ROLLBACK 目標 tick */
            target_tick?: number | null;
        };
        /** @enum {string} */
        OrderType: "MOVE" | "ENGAGE" | "RECON" | "RESUPPLY" | "POSTURE";
        /** @enum {string} */
        OrderStatus: "PENDING" | "VALIDATED" | "EXECUTING" | "COMPLETED" | "REJECTED" | "CANCELLED";
        OrderRequest: {
            unit_id: string;
            order_type: components["schemas"]["OrderType"];
            /** @description 依 order_type 而異：MOVE={to_h3,mobility_profile}；ENGAGE={target_unit_id,weapon_id?} */
            payload?: Record<string, never>;
        };
        PrecheckCheck: {
            name: string;
            passed: boolean;
            detail?: string;
        };
        PrecheckResult: {
            feasible: boolean;
            checks: components["schemas"]["PrecheckCheck"][];
            reason?: string | null;
        };
        OrderResponse: {
            id: string;
            unit_id: string;
            order_type: string;
            status: components["schemas"]["OrderStatus"];
            precheck?: components["schemas"]["PrecheckResult"] | null;
            issued_at_tick: number;
        };
    };
    responses: never;
    parameters: {
        SessionId: string;
        OrderId: string;
        TaskId: string;
        PluginName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description JWT pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role-filtered sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sessionLifecycle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUnits: {
        parameters: {
            query?: {
                /** @description White Cell 視角切換——以某陣營視角過濾（O7.4）；非全知者使用→403 */
                as_faction?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Units */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitView"][];
                };
            };
            /** @description Not a participant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    injectEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectRequest"];
            };
        };
        responses: {
            /** @description Injected */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectResponse"];
                };
            };
            /** @description Not White Cell */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sessionControl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlRequest"];
            };
        };
        responses: {
            /** @description Control event emitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectResponse"];
                };
            };
            /** @description Not White Cell */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"][];
                };
            };
            /** @description Not a participant */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    issueOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Order validated & queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation or physics precheck failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Terrain plugin unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
                oid: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Order not cancellable (illegal transition) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    aiConsult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    aiTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
                tid: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status/result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mselInject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Injected */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    queryLedger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAAR: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AAR report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenarios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validated & stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    togglePlugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["PluginName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Toggled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
